// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk4pOmj1ZgPK4QF9_prxJQ_Z9pMmBGYXk',
    appId: '1:299903922767:web:d0b0c799fabd1a67d9b03a',
    messagingSenderId: '299903922767',
    projectId: 'flutteractividad1',
    authDomain: 'flutteractividad1.firebaseapp.com',
    storageBucket: 'flutteractividad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeQW3FRp_YlCa3PZl8dZispoHG3Sag5dg',
    appId: '1:299903922767:android:b4b30acbeaacb5d4d9b03a',
    messagingSenderId: '299903922767',
    projectId: 'flutteractividad1',
    storageBucket: 'flutteractividad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QEHp0iKYdn_BzcTOvLRRskeCOnLDYXo',
    appId: '1:299903922767:ios:5dcd33706683c617d9b03a',
    messagingSenderId: '299903922767',
    projectId: 'flutteractividad1',
    storageBucket: 'flutteractividad1.appspot.com',
    iosBundleId: 'com.example.flutterActividad1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3QEHp0iKYdn_BzcTOvLRRskeCOnLDYXo',
    appId: '1:299903922767:ios:5dcd33706683c617d9b03a',
    messagingSenderId: '299903922767',
    projectId: 'flutteractividad1',
    storageBucket: 'flutteractividad1.appspot.com',
    iosBundleId: 'com.example.flutterActividad1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk4pOmj1ZgPK4QF9_prxJQ_Z9pMmBGYXk',
    appId: '1:299903922767:web:e9ea8fa444aecdd0d9b03a',
    messagingSenderId: '299903922767',
    projectId: 'flutteractividad1',
    authDomain: 'flutteractividad1.firebaseapp.com',
    storageBucket: 'flutteractividad1.appspot.com',
  );
}
